// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wyakemjxokrmeixlwuxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5YWtlbWp4b2tybWVpeGx3dXh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNTUxNTksImV4cCI6MjA2NTkzMTE1OX0.tOcEXrQ7sTP-KXEgZEPY4odnYPzZBkKaDXm-kGvqQ-s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);